## Generated by SimInf (v6.2.0) 2019-03-13 14:23

##' Class \code{SEIRe_sp}
##'
##' Class to handle the \code{SEIRe_sp} \code{SimInf_model}.
##' @export
setClass("SEIRe_sp", contains = "SimInf_model")

##' Create a model for the SimInf framework
##'
##' Create a model to be used by the SimInf framework.
##' @param ldata Data specific to each node in the model.
##'     Can be specified either as a numeric matrix where
##'     column \code{ldata[, j]} contains the local data
##'     vector for the node \code{j} or as a
##'     \code{data.frame} with one row per node.
##' @param gdata Data that are common to all nodes in the model.
##'     Can be specified either as a named numeric vector or as
##'     a one-row data.frame.
##' @param u0 A data.frame with the initial state in each node.
##' @param tspan A vector (length >= 2) of increasing time points
##'     where the state of each node is to be returned.
##' @param events A data.frame with scheduled events.
##' @import SimInf
##' @import methods
##' @export
##' @examples
##' ## Please add example(s) how to use the model
SEIRe_sp <- function(ldata = NULL, gdata = NULL, u0 = NULL, tspan = NULL, events = NULL)
{
    ## Check ldata
    ldata_names <- c("phi", "end_t1", "end_t2", "end_t3", "end_t4")
    if (is.data.frame(ldata)) {
        if (!all(ldata_names %in% colnames(ldata)))
            stop("Missing parameter(s) in 'ldata'")
        ldata <- ldata[, ldata_names, drop = FALSE]
    } else if (is.matrix(ldata)) {
        if (!all(ldata_names %in% rownames(ldata)))
            stop("Missing parameter(s) in 'ldata'")
        ldata <- ldata[ldata_names, , drop = FALSE]
    } else {
        stop("'ldata' must either be a 'data.frame' or a 'matrix'.")
    }

    ## Check gdata
    gdata_names <- c("beta", "upsilon", "epsilon", "gamma", "beta_t1", "beta_t2", "beta_t3", "beta_t4")
    if (is.data.frame(gdata)) {
        if (!all(gdata_names %in% colnames(gdata)))
            stop("Missing parameter(s) in 'gdata'")
        gdata <- gdata[, gdata_names, drop = FALSE]
    } else if (is.atomic(gdata) && is.numeric(gdata)) {
        if (!all(gdata_names %in% names(gdata)))
            stop("Missing parameter(s) in 'gdata'")
        gdata <- gdata[gdata_names]
    } else {
        stop("'gdata' must either be a 'data.frame' or a 'numeric' vector.")
    }

    ## Check u0
    compartments <- c("S", "E", "I", "R")
    if (is.null(u0))
        stop("'u0' must be specified.")
    if (!is.data.frame(u0))
        u0 <- as.data.frame(u0)
    if (!all(compartments %in% names(u0)))
        stop("Missing columns in u0")
    u0 <- u0[, compartments, drop = FALSE]

    G <- structure(c(1, 1, 0, 1, 1, 1, 1, 0, 1), .Dim = c(3L, 3L), .Dimnames = list(
        c("S -> E", "E -> I", "I -> R"), c("1", "2", "3")))

    S <- structure(c(-1, 1, 0, 0, 0, -1, 1, 0, 0, 0, -1, 1), .Dim = c(4L, 
    3L), .Dimnames = list(c("S", "E", "I", "R"), c("1", "2", "3")))

    E <- structure(numeric(0), .Dim = c(0L, 0L), .Dimnames = list(NULL, 
        NULL))

    N <- structure(integer(0), .Dim = c(0L, 0L))

    model <- SimInf_model(ldata = ldata, gdata = gdata, G = G, S = S, E = E, N = N,
                          tspan = tspan, events = events, u0 = u0)

    as(model, "SEIRe_sp")
}

##' Run the model
##'
##' @rdname run-methods
##' @param model The model to run.
##' @param threads Number of threads. Default is NULL, i.e. to use all
##'     available processors.
##' @param solver Which numerical solver to utilize. Default is NULL,
##'     i.e., use the default numerical solver in SimInf.
##' @return SimInf_model with result from simulation.
##' @export
##' @useDynLib SEIRe_sp, .registration=TRUE
setMethod("run",
    signature(model = "SEIRe_sp"),
    function(model, threads = NULL, solver = NULL)
    {
        methods::validObject(model)
       .Call(SimInf_model_run, model, threads, solver, PACKAGE = "SEIRe_sp")
    })
